In [1]:
%matplotlib inline
import matplotlib
import pandas
import matplotlib.pyplot as plt

In [2]:
price = pandas.read_csv('close-prices.csv')
index = pandas.read_csv('djia-index.csv')

In [3]:
price.head()

date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
3  2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
4  2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

          DD        DIS         GE          GS    ...            PFE  \
0  59.409999  64.750000  24.280001  165.250000    ...      28.799999   
1  59.319997  64.320000  24.320000  162.970001    ...      28.709999   
2  59.319997  64.449997  24.230000  162.309998    ...      28.490000   
3  59.509996  65.239998  24.250000  162.289993    ...      28.520000   
4  59.009995  65.190002  24.049999  159.850006    ...      28.879999   

          PG          T        TRV        UNH         UTX           V  \
0  79.279999  34.220001  86.379997  71.820000  109.419998  196.240005   
1  78.620003  34.090000  85.870003  72.320000  110.000000  193.339996   
2  77.720001  34.049999  85.980003  71.980003  109.260002  191.559998   
3  78.050003  34.230000  85.830002  72.160004  109.660004  193.559998   
4  77.209999  33.980000  85.410004  71.989998  109.360001  193.050003   

          VZ        WMT        XOM  
0  47.980000  76.419998  87.750000  
1  47.270000  75.750000  87.360001  
2  46.950001  74.650002  87.139999  
3  47.669998  74.620003  87.070000  
4  47.000000  74.360001  86.900002  

[5 rows x 31 columns]

In [4]:
index.head()

date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [5]:
from sklearn import decomposition

In [6]:
pca = decomposition.PCA(n_components=10)

In [7]:
price_1 = price.copy()

In [8]:
price_1 = price_1.drop('date', axis=1)

In [9]:
price_result = pca.fit(price_1)

In [10]:
pca.explained_variance_ratio_

array([ 0.73897118,  0.11007169,  0.04995088,  0.0287492 ,  0.02215448,
        0.01931577,  0.00674853,  0.00614091,  0.00320594,  0.00305611])

In [11]:
summary = 0
for i in range(len(pca.explained_variance_ratio_)):
    summary += pca.explained_variance_ratio_[i]
    print summary
    print i+1

0.738971182715
1
0.849042872814
2
0.898993755584
3
0.927742953784
4
0.949897432663
5
0.969213199174
6
0.975961730737
7
0.982102640924
8
0.985308582609
9
0.988364692911
10


In [12]:
pca.components_[0] 

array([  1.61383840e-02,   1.20644923e-01,  -5.16612711e-02,
         5.04842369e-02,  -1.25859933e-01,   1.14089567e-01,
         2.33906290e-01,  -6.20513749e-03,   2.51227032e-01,
         2.88996029e-01,  -2.64998795e-01,   9.31320168e-02,
         9.13948403e-02,   4.69879340e-02,   2.90549417e-02,
        -2.61068828e-02,   3.29615584e-01,   7.13897133e-02,
         7.62295699e-02,   2.11888868e-01,   2.30922941e-02,
         7.77316954e-02,  -7.20594590e-03,   1.89479745e-01,
         3.21564017e-01,   5.36834873e-02,   5.79683946e-01,
         1.09122230e-04,   8.71614334e-02,  -4.29421420e-02])

In [13]:
index_1 = index.copy()

In [14]:
max(pca.components_[0])

0.5796839457473606

In [15]:
index_1 = index.drop('date', axis=1)

In [16]:
import numpy as np

In [17]:
len(index_1)

374

In [18]:
pca.components_[0]

array([  1.61383840e-02,   1.20644923e-01,  -5.16612711e-02,
         5.04842369e-02,  -1.25859933e-01,   1.14089567e-01,
         2.33906290e-01,  -6.20513749e-03,   2.51227032e-01,
         2.88996029e-01,  -2.64998795e-01,   9.31320168e-02,
         9.13948403e-02,   4.69879340e-02,   2.90549417e-02,
        -2.61068828e-02,   3.29615584e-01,   7.13897133e-02,
         7.62295699e-02,   2.11888868e-01,   2.30922941e-02,
         7.77316954e-02,  -7.20594590e-03,   1.89479745e-01,
         3.21564017e-01,   5.36834873e-02,   5.79683946e-01,
         1.09122230e-04,   8.71614334e-02,  -4.29421420e-02])

In [20]:
index_tr = pca.transform(index_1)
price_tr = pca.transform(price_1)

In [22]:
result_index = []
for i in price_tr:
    result_index.append(i[0])

In [23]:
np.array(result_index)

array([-50.90240358, -52.84690919, -54.61443917, -52.60056628,
       -52.3701233 , -54.65341197, -52.81257496, -53.6511457 ,
       -56.69272698, -54.40265506, -58.33164549, -61.71626498,
       -61.31940025, -53.79252445, -50.89263448, -49.63740755,
       -52.3876147 , -47.47854294, -43.56033499, -42.55928046,
       -42.45027087, -42.27124797, -43.25272816, -40.05934481,
       -38.49726315, -39.06492263, -38.39304378, -38.40055833,
       -42.38616981, -39.83057417, -41.29548604, -40.43554958,
       -38.49607932, -42.96158052, -38.71252143, -38.83379331,
       -39.90606174, -37.58824522, -34.92356725, -32.96232694,
       -34.52461722, -36.40345948, -37.22194659, -32.95883861,
       -30.59159319, -29.63686919, -27.34513869, -26.90264007,
       -27.41985754, -28.24277351, -31.79501246, -31.39698179,
       -33.14502283, -30.41497345, -30.73495319, -32.3505575 ,
       -30.84313809, -32.84916115, -30.36248061, -29.89452878,
       -25.10690112, -19.92249325, -19.83315396, -19.22

In [24]:
ind = np.genfromtxt('djia-index.csv',delimiter=',',skip_header=1)

In [25]:
ind_1 = ind[:,1:]

In [26]:
ind_1[373][0]

18076.189452999999

In [27]:
result_index_1 = []
for i in ind_1:
    result_index_1.append(i[0])

In [28]:
result_index_1

[15401.379883,
 15334.589844,
 15273.259765999999,
 15328.299805000001,
 15258.240234000001,
 15129.669921999999,
 15191.700194999999,
 15133.139648,
 14996.480469,
 15072.580078000001,
 14936.240234000001,
 14776.530273,
 14802.980469,
 15126.070312,
 15237.110352,
 15301.259765999999,
 15168.009765999999,
 15373.830078000001,
 15371.650390999999,
 15399.650390999999,
 15392.200194999999,
 15467.660156,
 15413.330078000001,
 15509.209961,
 15570.280273,
 15568.929688,
 15680.349609000001,
 15618.759765999999,
 15545.75,
 15615.549805000001,
 15639.120117,
 15618.219727,
 15746.879883,
 15593.980469,
 15761.780273,
 15783.099609000001,
 15750.669921999999,
 15821.629883,
 15876.219727,
 15961.700194999999,
 15976.019531,
 15967.030273,
 15900.820312,
 16009.990234000001,
 16064.769531,
 16072.540039,
 16072.799805000001,
 16097.330078000001,
 16086.410156,
 16008.769531,
 15914.620117,
 15889.769531,
 15821.509765999999,
 16020.200194999999,
 16025.530273,
 15973.129883,
 15843.530273,

In [34]:
round(np.corrcoef(result_index,result_index_1)[1][0],2)

0.91

In [ ]:
price_result